import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from typing import Dict, Any, List
import json
import asyncio

import aiofiles

from autogen_core import (MessageContext, RoutedAgent, SingleThreadedAgentRuntime, TopicId, message_handler, type_subscription, ClosureAgent, ClosureContext)

from autogen_core.models import  SystemMessage, UserMessage
from autogen_core._default_subscription import DefaultSubscription
from autogen_core._default_topic import DefaultTopicId
from config import azure_client
from prompts_qlikview import EXTRACTION_PROMPTS

from langchain_core.output_parsers import JsonOutputParser

parser = JsonOutputParser()

# ---------------------------------------------------------------------------
# Duplicate-literal constants
# ---------------------------------------------------------------------------
_KEY_DATA_SOURCES = "Data Sources"
_KEY_DATA_MODEL = "Data Model"
_KEY_DATA_TRANSFORMATIONS = "Data Transformations"
_KEY_PARAMS_VARS = "Parameters or Variables"


@dataclass
class FlowRequest:
    content: str
    extraction_type: str

@dataclass
class Request:
    content: str

@dataclass
class TaskResponse:
    content: json

@dataclass
class ExecutiveSummaryResponse:
    content: str

def _make_collect_result(q: asyncio.Queue) -> object:
    """Return a closure that drains TaskResponse messages into *q*."""
    async def collect_result(
        _agent: ClosureContext, message: TaskResponse, ctx: MessageContext
    ) -> None:
        await q.put(message)
    return collect_result


def _make_save_executive_summary(q: asyncio.Queue) -> object:
    """Return a closure that drains ExecutiveSummaryResponse messages into *q*."""
    async def save_executive_summary(
        _agent: ClosureContext, message: ExecutiveSummaryResponse, ctx: MessageContext
    ) -> None:
        await q.put(message)
    return save_executive_summary


# Single Agent for all extractions
@type_subscription(topic_type="QlikViewMetadataExtractor")
class QlikViewMetadataExtractorAgent(RoutedAgent):
    def __init__(self) -> None:
        super().__init__("QlikView Metadata Extractor Agent")

    @message_handler
    async def handle_message(self, message: FlowRequest, ctx: MessageContext) -> None:
        print(f"\n{'='*60}\nAgent {self.id} processing {message.extraction_type}...\n")
        if ctx.topic_id is None:
            raise ValueError("Topic ID is required for broadcasting.")
        try:
            agent_prompt = EXTRACTION_PROMPTS.get(message.extraction_type)
            if not agent_prompt:
                raise ValueError(f"Unknown extraction type: {message.extraction_type}")

            messages = [
                SystemMessage(content=agent_prompt),
                UserMessage(content=message.content, source="user")
            ]

            print("---------------------------------", agent_prompt)
            print("---------------------------------", message.content)

            response = await azure_client.create(messages=messages)
            metadata_json = response.content

            print(f"\n--- Extracted {message.extraction_type} Metadata ---\n{metadata_json}\n{'='*60}")

            if isinstance(metadata_json, str):
                metadata_json = parser.parse(metadata_json)

            await self.publish_message(
                message=TaskResponse(content=json.dumps(metadata_json)),
                topic_id=DefaultTopicId(),
            )
        except Exception as e:
            print(f"Error in {self.id} for {message.extraction_type}: {e}")
            raise ValueError(f"Failed to process {message.extraction_type} extraction.")

executive_summary_topic_type = "ExecutiveSummaryAgent"

@type_subscription(topic_type=executive_summary_topic_type)
class ExecutiveSummaryAgent(RoutedAgent):
    def __init__(self) -> None:
        super().__init__("A Executive Summary agent.")
        self._system_messages = [SystemMessage(
            content="""
                Role: Data Executive Summary Specialist
                From the extraction response generated by analyzing a Qlikview dashboard, please generate an executive summary. 
                Emphasize how the dashboard supports decision-making, what insights it reveals, and how it contributes to operational or strategic goals. Maintain a professional tone suitable for executive stakeholders.
                Executive Summary Template (for structure only, do NOT copy text verbatim):
                Title: "Executive Summary: [Brief Purpose or Scope]"
                You are a business analyst skilled in interpreting BI tool configurations. Based on the provided data model, visualizations, and transformations from a QlikView dashboard JSON-like structure, generate an executive summary suitable for inclusion in a Business Requirements Document (BRD). 
                Avoid technical implementation details such as fields, expressions, tools, or specific formatting parameters. Focus only on the business perspective: what insights are being tracked, which KPIs are being monitored, what business questions are being answered, and how the dashboard supports decision-making.
                Keep it factual, organized, and insight-oriented.
                This summary captures the high-level objectives and outcomes of the data preparation process, underscoring its role in driving actionable insights and supporting informed decision-making.                    
            """    
        )]

    @message_handler
    async def handle_message(self, message: Request, ctx: MessageContext) -> None:
        print(f"\n{'='*50}\nProcessor {self.id} handling component: Creating Executive Summary")
        if ctx.topic_id is None:
                raise ValueError("Topic ID is required for broadcasting.")
        try:
            flow_data = message.content
            agent_prompt = next((msg.content for msg in self._system_messages), None)
            if not agent_prompt:
                raise ValueError("System prompt is missing for agent processing.")
            messages = [
                SystemMessage(content=agent_prompt),
                UserMessage(content=flow_data, source="user")
            ]
            response = await azure_client.create(messages=messages)

            print(response.content)
            await self.publish_message(ExecutiveSummaryResponse(content=response.content), topic_id=DefaultTopicId())
        except json.JSONDecodeError:
            raise ValueError("Invalid JSON format in the Tableau Prep flow file.")


# ---------------------------------------------------------------------------
# Helper: build categorised file lists from raw file_paths
# ---------------------------------------------------------------------------

def _build_file_maps(file_paths: List[str]) -> dict:
    """Return a dict of all categorised file lists derived from file_paths."""
    visualization_prefixes = ["TB", "CH", "CS", "TX"]
    filter_prefixes = ["LB", "MB"]
    object_prefixes = [
        "TB", "CH", "CS", "TX",
        "BU", "IB", "SL", "BM", "CT", "SO",
        "LB", "MB",
    ]
    dashboards_prefixes = ["SH"]
    sheet_prefixes = ["SH"]

    return {
        "data_extract_files": [p for p in file_paths if p.endswith("LoadScript.txt")],
        "visualization_files": [p for p in file_paths if os.path.basename(p).startswith(tuple(visualization_prefixes))],
        "param_variable_files": [p for p in file_paths if p.endswith(("AllProperties.xml", "DocInternal.xml"))],
        "dashboards_files": [p for p in file_paths if os.path.basename(p).startswith(tuple(dashboards_prefixes))],
        "filter_files": [p for p in file_paths if os.path.basename(p).startswith(tuple(filter_prefixes))],
        "sheet_files": [p for p in file_paths if os.path.basename(p).startswith(tuple(sheet_prefixes))],
        "object_files": [p for p in file_paths if os.path.basename(p).startswith(tuple(object_prefixes))],
        "hierarchies_files": [p for p in file_paths if p.endswith("AllProperties.xml")],
    }


# ---------------------------------------------------------------------------
# Helper: extract object names from XML files
# ---------------------------------------------------------------------------

def _extract_name_from_ch_file(file_path: str) -> str:
    tree = ET.parse(file_path)
    root = tree.getroot()
    name_value = root.findtext(".//Name/v")
    if name_value is None:
        name_value = root.findtext(".//Text/v")
    return name_value


def _extract_object_names(object_files: List[str]) -> dict:
    """Return {object_id: name} for all object XML files that have a name."""
    names = {}
    for path in object_files:
        object_id = os.path.basename(path)
        name = _extract_name_from_ch_file(path)
        if name:
            names[object_id] = name
    return names


# ---------------------------------------------------------------------------
# Helpers: publish file groups to the runtime
# ---------------------------------------------------------------------------

async def _publish_visualization_files(
    runtime,
    visualization_files: List[str],
    file_contents: str,
) -> None:
    for sheet_path in visualization_files:
        async with aiofiles.open(sheet_path, 'r', encoding="utf-8") as f:
            file_content = await f.read()
        print(file_content)
        content = (
            f"Object_ID: {sheet_path.split('/')[-1].replace('.xml', '').upper()}\n"
            f"QlikViewProjectXML:\n{file_contents}\n"
            f"VisualizationObjectXML:\n{file_content}\n"
        )
        print(content)
        await runtime.publish_message(
            FlowRequest(content=content, extraction_type="visualizations"),
            topic_id=TopicId("QlikViewMetadataExtractor", source="default")
        )


async def _publish_filter_files(
    runtime,
    filter_files: List[str],
    file_contents: str,
) -> None:
    for sheet_path in filter_files:
        async with aiofiles.open(sheet_path, 'r', encoding="utf-8") as f:
            file_content = await f.read()
        print(file_content)
        content = (
            f"Object_ID: {sheet_path.split('/')[-1].replace('.xml', '').upper()}\n"
            f"QlikViewProjectXML:\n{file_contents}\n"
            f"FilterObjectXML:\n{file_content}\n"
        )
        print(content)
        await runtime.publish_message(
            FlowRequest(content=content, extraction_type="filters"),
            topic_id=TopicId("QlikViewMetadataExtractor", source="default")
        )


async def _publish_dashboard_files(
    runtime,
    dashboards_files: List[str],
    file_contents: str,
    names: dict,
) -> None:
    for sheet_path in dashboards_files:
        async with aiofiles.open(sheet_path, 'r', encoding="utf-8") as f:
            file_content = await f.read()
        print(file_content)
        content = (
            f"Object_ID: {os.path.basename(sheet_path).replace('.xml', '').upper()}\n"
            f"QlikViewProjectXML:\n{file_contents}\n"
            f"ObjectXML:\n{file_content}\n"
            f"names and object id: {names}\n"
        )
        print(content)
        await runtime.publish_message(
            FlowRequest(content=content, extraction_type="dashboards"),
            topic_id=TopicId("QlikViewMetadataExtractor", source="default")
        )


async def _publish_sheet_files(runtime, sheet_files: List[str]) -> None:
    for sheet_path in sheet_files:
        async with aiofiles.open(sheet_path, 'r', encoding="utf-8") as f:
            file_content = await f.read()
        print(file_content)
        content = (
            f"Object_ID: {os.path.basename(sheet_path).replace('.xml', '').upper()}\n"
            f"VisualizationObjectXML:\n{file_content}\n"
        )
        print(content)
        await runtime.publish_message(
            FlowRequest(content=content, extraction_type="sheets"),
            topic_id=TopicId("QlikViewMetadataExtractor", source="default")
        )


async def _publish_hierarchy_files(runtime, hierarchies_files: List[str]) -> None:
    for sheet_path in hierarchies_files:
        async with aiofiles.open(sheet_path, 'r', encoding="utf-8") as f:
            file_content = await f.read()
        await runtime.publish_message(
            FlowRequest(content=file_content, extraction_type="hierarchies"),
            topic_id=TopicId("QlikViewMetadataExtractor", source="default")
        )


# ---------------------------------------------------------------------------
# Helpers: aggregate queue results
# ---------------------------------------------------------------------------

# Module-level mapping: JSON result key -> aggregated_results key
_PHASE1_KEY_MAP = {
    "data_sources":           _KEY_DATA_SOURCES,
    "data_model":             _KEY_DATA_MODEL,
    "data_transformations":   _KEY_DATA_TRANSFORMATIONS,
    "hierarchies":            "Hierarchies",
    "Visualizations":         "Visualizations",
    "filters":                "Filters",
    "parameters_variables":   _KEY_PARAMS_VARS,
    "sheets":                 "Sheets",
    "dashboards":             "Dashboards",
    "relationships":          "Relationships",
    "tables":                 "Enhanced Tables",
    "calculations":           "Calculation Dependencies",
}


async def _aggregate_phase1_results(q: asyncio.Queue) -> dict:
    """Drain the queue and return the aggregated Phase 1 results dict."""
    aggregated_results = {v: [] for v in _PHASE1_KEY_MAP.values()}

    while not q.empty():
        result = await q.get()
        result_json = json.loads(result.content)
        print("result_json:", result_json)

        for src_key, dst_key in _PHASE1_KEY_MAP.items():
            if src_key in result_json:
                aggregated_results[dst_key].extend(result_json[src_key])

    return aggregated_results


async def _run_phase2_extraction(
    runtime,
    aggregated_results: dict,
    loadscript_content: str,
) -> None:
    """Publish all Phase 2 (enhanced extraction) messages to the runtime."""
    context_for_enhancement = {
        "data_sources": aggregated_results[_KEY_DATA_SOURCES],
        "data_model": aggregated_results[_KEY_DATA_MODEL],
        "data_transformations": aggregated_results[_KEY_DATA_TRANSFORMATIONS],
        "visualizations": aggregated_results["Visualizations"],
        "parameters_variables": aggregated_results[_KEY_PARAMS_VARS],
    }

    print("\n--- Extracting Data Sources (Common Model Format) ---")
    data_sources_context = (
        f"Data Sources (Phase 1):\n"
        f"{json.dumps(context_for_enhancement['data_sources'], indent=2)}\n\n"
        f"LoadScript:\n{loadscript_content}\n"
    )
    await runtime.publish_message(
        FlowRequest(content=data_sources_context, extraction_type="data_sources_common"),
        topic_id=TopicId("QlikViewMetadataExtractor", source="enhanced")
    )

    print("\n--- Extracting Relationships ---")
    relationships_context = (
        f"LoadScript:\n{loadscript_content}\n\n"
        f"Data Model:\n{json.dumps(context_for_enhancement['data_model'], indent=2)}\n\n"
        f"Visualizations (showing field usage):\n"
        f"{json.dumps(context_for_enhancement['visualizations'], indent=2)}\n"
    )
    await runtime.publish_message(
        FlowRequest(content=relationships_context, extraction_type="relationships"),
        topic_id=TopicId("QlikViewMetadataExtractor", source="enhanced")
    )

    print("\n--- Extracting Enhanced Table Metadata ---")
    enhanced_tables_context = (
        f"Data Model:\n{json.dumps(context_for_enhancement['data_model'], indent=2)}\n\n"
        f"LoadScript:\n{loadscript_content}\n\n"
        f"Data Transformations:\n"
        f"{json.dumps(context_for_enhancement['data_transformations'], indent=2)}\n\n"
        f"Visualizations (showing field usage):\n"
        f"{json.dumps(context_for_enhancement['visualizations'], indent=2)}\n"
    )
    await runtime.publish_message(
        FlowRequest(content=enhanced_tables_context, extraction_type="enhanced_tables"),
        topic_id=TopicId("QlikViewMetadataExtractor", source="enhanced")
    )

    print("\n--- Extracting Calculation Dependencies ---")
    calculations_context = (
        f"Data Transformations:\n"
        f"{json.dumps(context_for_enhancement['data_transformations'], indent=2)}\n\n"
        f"Visualizations (with chart expressions):\n"
        f"{json.dumps(context_for_enhancement['visualizations'], indent=2)}\n\n"
        f"Parameters or Variables:\n"
        f"{json.dumps(context_for_enhancement['parameters_variables'], indent=2)}\n\n"
        f"LoadScript (for inline calculations):\n{loadscript_content}\n"
    )
    await runtime.publish_message(
        FlowRequest(content=calculations_context, extraction_type="calculation_dependencies"),
        topic_id=TopicId("QlikViewMetadataExtractor", source="enhanced")
    )


async def _collect_phase2_results(q: asyncio.Queue) -> dict:
    """Drain the queue and return Phase 2 results in Common Model format."""
    phase2_results = {
        "data_sources": [],
        "tables": [],
        "relationships": [],
        "calculations": [],
    }

    while not q.empty():
        result = await q.get()
        result_json = json.loads(result.content)

        if "data_sources" in result_json:
            phase2_results["data_sources"].extend(result_json["data_sources"])
        if "relationships" in result_json:
            phase2_results["relationships"].extend(result_json["relationships"])
        if "tables" in result_json:
            phase2_results["tables"].extend(result_json["tables"])
        if "calculations" in result_json:
            phase2_results["calculations"].extend(result_json["calculations"])

    return phase2_results


# ---------------------------------------------------------------------------
# Main orchestration function
# ---------------------------------------------------------------------------

async def run_single_tenant_flow_processor(file_paths):

    file_maps = _build_file_maps(file_paths)
    data_extract_files = file_maps["data_extract_files"]
    visualization_files = file_maps["visualization_files"]
    param_variable_files = file_maps["param_variable_files"]
    dashboards_files = file_maps["dashboards_files"]
    filter_files = file_maps["filter_files"]
    sheet_files = file_maps["sheet_files"]
    object_files = file_maps["object_files"]
    hierarchies_files = file_maps["hierarchies_files"]

    names = _extract_object_names(object_files)
    print(names)

    # Per-call queues — avoids cross-contamination when batch processes
    # multiple QlikView files concurrently.
    result_queue: asyncio.Queue[TaskResponse] = asyncio.Queue()
    exe_queue: asyncio.Queue[ExecutiveSummaryResponse] = asyncio.Queue()

    # Setup Autogen Core runtime
    runtime = SingleThreadedAgentRuntime()

    # Register single agent
    await QlikViewMetadataExtractorAgent.register(
        runtime,
        type="QlikViewMetadataExtractor",
        factory=lambda: QlikViewMetadataExtractorAgent(),
    )

    # ExecutiveSummaryAgent is only used later in its own runtime invocation;
    # do NOT register save_executive_summary here — it would receive TaskResponse
    # messages and log spurious type-mismatch warnings.
    await ClosureAgent.register_closure(
        runtime,
        "collect_result_agent",
        _make_collect_result(result_queue),
        subscriptions=lambda: [DefaultSubscription()],
    )

    async def process_files(file_map: dict, runtime, topic_name="QlikViewMetadataExtractor", source="default"):
        for extraction_type, files in file_map.items():
            for file_path in files:
                try:
                    async with aiofiles.open(file_path, 'r', encoding="utf-8") as f:
                        content = await f.read()
                    print(f"\nProcessing {extraction_type} file: {file_path}")
                    await runtime.publish_message(
                        FlowRequest(content=content, extraction_type=extraction_type),
                        topic_id=TopicId(topic_name, source=source)
                    )
                except Exception as e:
                    print(f"Error processing {file_path} for {extraction_type}: {e}")

    file_map = {
        "dataextractor": data_extract_files,
        "parameters_variables": param_variable_files,
    }

    runtime.start()

    await process_files(file_map, runtime)

    file_path = [path for path in file_paths if path.endswith(("QlikViewProject.xml"))]
    async with aiofiles.open(file_path[0], 'r', encoding="utf-8") as file:
        file_contents = await file.read()

    await _publish_visualization_files(runtime, visualization_files, file_contents)
    await _publish_filter_files(runtime, filter_files, file_contents)
    await _publish_dashboard_files(runtime, dashboards_files, file_contents, names)
    await _publish_sheet_files(runtime, sheet_files)
    await _publish_hierarchy_files(runtime, hierarchies_files)

    await runtime.stop_when_idle()

    # Aggregate Phase 1 results
    aggregated_results = await _aggregate_phase1_results(result_queue)

    # ============================================================================
    # PHASE 2: ENHANCED EXTRACTION (Relationships, Enhanced Tables, Calculations)
    # ============================================================================
    print("\n" + "="*80)
    print("PHASE 2: Running Enhanced Extraction for Common Model Alignment")
    print("="*80 + "\n")

    runtime.start()

    # Get LoadScript content for enhanced extraction
    loadscript_content = ""
    if data_extract_files:
        async with aiofiles.open(data_extract_files[0], 'r', encoding="utf-8") as f:
            loadscript_content = await f.read()

    await _run_phase2_extraction(runtime, aggregated_results, loadscript_content)

    await runtime.stop_when_idle()

    # Collect Phase 2 results
    print("\n--- Collecting Phase 2 Results (Common Model Format) ---")
    phase2_results = await _collect_phase2_results(result_queue)

    print("\n" + "="*80)
    print("Phase 2 Extraction Complete (Common Model Format)!")
    print(f"  - Data Sources: {len(phase2_results['data_sources'])}")
    print(f"  - Tables: {len(phase2_results['tables'])}")
    print(f"  - Relationships: {len(phase2_results['relationships'])}")
    print(f"  - Calculations: {len(phase2_results['calculations'])}")
    print("="*80 + "\n")

    # Continue with executive summary generation in a dedicated runtime
    exe_runtime = SingleThreadedAgentRuntime()
    await ExecutiveSummaryAgent.register(
        exe_runtime,
        type=executive_summary_topic_type,
        factory=lambda: ExecutiveSummaryAgent(),
    )
    await ClosureAgent.register_closure(
        exe_runtime,
        "save_executive_summary",
        _make_save_executive_summary(exe_queue),
        subscriptions=lambda: [DefaultSubscription()],
    )
    exe_runtime.start()

    await exe_runtime.publish_message(
        Request(content=json.dumps(aggregated_results)),
        topic_id=TopicId(executive_summary_topic_type, source="default"),
    )

    await exe_runtime.stop_when_idle()

    while not exe_queue.empty():
        data = (await exe_queue.get()).content
        print("----------------------", data)
        aggregated_results["executivesummary"] = data

    # ============================================================================
    # MERGE PHASE 1 + PHASE 2 INTO COMMON MODEL
    # ============================================================================
    print("\n" + "="*80)
    print("Merging Phase 1 + Phase 2 into Common Model")
    print("="*80 + "\n")

    from common_model_merger import merge_qlikview_results

    common_model = merge_qlikview_results(
        phase1_output=aggregated_results,
        phase2_output=phase2_results
    )

    # Carry the executive/technical summary into the final model so handlers
    # can derive ai_summary from it.
    common_model["technical_summary"] = aggregated_results.get("executivesummary", "")

    print("✅ Common Model merge complete!")
    print("="*80 + "\n")

    return common_model
