table InsuranceData
	lineageTag: ce082514-4e1b-46fb-88f1-06bef0825837

	column PolicyNumber
		dataType: string
		lineageTag: d5d7952c-572e-4f58-9279-e0620e2a6e6d
		summarizeBy: none
		sourceColumn: PolicyNumber

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: 70aef21c-2584-4b21-9cbe-a7e42cf13ba2
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 6795f781-7954-431e-849a-0a81d27b58dc
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: ad2f30a5-62f8-4de9-8898-f1ed9f602c71
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column PolicyType
		dataType: string
		lineageTag: a0f1bf8a-5725-41af-b714-bb056908e098
		summarizeBy: none
		sourceColumn: PolicyType

		annotation SummarizationSetBy = Automatic

	column PolicyStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e88595a-bb76-4494-9858-11282ce2d53d
		summarizeBy: none
		sourceColumn: PolicyStartDate

		variation Variation
			isDefault
			relationship: 6422d9c7-9526-4e33-956c-53692295c179
			defaultHierarchy: LocalDateTable_269b0c83-794d-4ee9-b80a-c24d4ead41a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PolicyEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c3d00a40-e59b-482b-a746-21e22defb815
		summarizeBy: none
		sourceColumn: PolicyEndDate

		variation Variation
			isDefault
			relationship: 79f8e7fc-4590-4cc1-bf34-b92c4d8024f4
			defaultHierarchy: LocalDateTable_192cd601-d1ef-4c52-991e-060640b2e5d7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PremiumAmount
		dataType: double
		lineageTag: e9d7338e-7862-4ead-a806-60b73343352f
		summarizeBy: sum
		sourceColumn: PremiumAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CoverageAmount
		dataType: double
		lineageTag: e0212bd2-713f-4ce3-a04e-64df5d64341d
		summarizeBy: sum
		sourceColumn: CoverageAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ClaimNumber
		dataType: string
		lineageTag: b812413d-c2c2-4f3e-bb61-4fec895e958f
		summarizeBy: none
		sourceColumn: ClaimNumber

		annotation SummarizationSetBy = Automatic

	column ClaimDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 03334666-300e-4a23-9988-5d04513e9bf8
		summarizeBy: none
		sourceColumn: ClaimDate

		variation Variation
			isDefault
			relationship: adaed340-e080-4fb4-aea8-713a7dcaaa24
			defaultHierarchy: LocalDateTable_c4890891-7a01-4297-a586-f4e4dc719b2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ClaimAmount
		dataType: double
		lineageTag: 76957d09-c58b-46c9-ae93-41f362f21762
		summarizeBy: sum
		sourceColumn: ClaimAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ClaimStatus
		dataType: string
		lineageTag: 828a4bc5-fe70-4836-8ffe-4a052b932a92
		summarizeBy: none
		sourceColumn: ClaimStatus

		annotation SummarizationSetBy = Automatic

	column 'Age Group'
		dataType: string
		lineageTag: 19860381-e914-4ec5-abb9-5abf6a8b6352
		summarizeBy: none
		sourceColumn: Age Group

		annotation SummarizationSetBy = Automatic

	column Active/Inactive
		dataType: string
		lineageTag: f13c1b4a-ba97-4817-a243-d276de714ebf
		summarizeBy: none
		sourceColumn: Active/Inactive

		annotation SummarizationSetBy = Automatic

	partition InsuranceData = m
		mode: import
		source =
				let
				    Source = Sql.Databases("SASWATI"),
				    Insurancedb = Source{[Name="Insurancedb"]}[Data],
				    dbo_InsuranceData = Insurancedb{[Schema="dbo",Item="InsuranceData"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_InsuranceData, each true),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Age", Int64.Type}, {"ClaimDate", type date}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Age Group", each if [Age] <= 25 then "Young Adult" else if [Age] <= 60 then "Adult" else "Elder"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Age Group", type text}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type1", "Active/Inactive", each if [PolicyEndDate] <= #date(2024, 12, 10) then "Inactive" else "Active"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Active/Inactive", type text}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

